config/routes.rb
Rails.application.routes.draw do
  resources :apartments
  resources :searches
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :user
  validates_numericality_of :paths, :greater_than => -0.1
  validates_numericality_of :rooms, :greater_than => -0.1
  self.per_page = 10

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord

  def apartments
    @apartments ||= find_apartments
  end

  private
  def find_apartments
    apartments = Apartment.all
     if pathes.present?
       puts "****************************************"
     else
       puts "------------------------------"

     end
    apartments = apartments.where("destination like ?", "%#{destnation}%") if destnation.present?
    apartments = apartments.where("paths = ?", pathes) if pathes.present?
    apartments = apartments.where("rooms = ?", rooms) if rooms.present?
    apartments
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.paginate(:page => params[:page])
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.user = current_user
    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:rooms, :paths, :destination)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number])

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
  end

  def create
    @search = Search.create!(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
    params.require(:search).permit(:rooms, :pathes, :destnation)
  end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/apartments/_form.html.erb
<%= bootstrap_form_for(apartment, local: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.number_field :rooms, placeholder:  "Number of Rooms..." %>
  </div>

  <div class="field">
    <%= form.number_field :paths, placeholder:  "Number of Pathrooms..." %>
  </div>

  <div class="field">
    <%= form.text_field :destination, placeholder:  "Enter the destination..."%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<a class="btn btn-outline-dark my-2 my-sm-0  float-right  role="button"
  <%= link_to 'Add Apartment', new_apartment_path %>
</a>
<h1>Apartments</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Destination</th>
      <th>Owner Name</th>
      <th>Owner phone</th>
      <th>Rooms</th>
      <th>Paths</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.destination %></td>
        <td><%= apartment.user.name %></td>
        <td><%= apartment.user.phone_number %></td>
        <td><%= apartment.rooms %></td>
        <td><%= apartment.paths %></td>
        <td>
          <a class="btn btn-info my-2 my-sm-0  float-right  role="button"
            <%= link_to 'Show', apartment %></td>
          </a>
        <%if current_user && current_user.id == apartment.user.id %>
          <td>
            <a class="btn btn-secondary my-2 my-sm-0  float-right  role="button"
              <%= link_to 'Edit', edit_apartment_path(apartment) %></td>
            </a>
          <td>
            <a class="btn btn-danger my-2 my-sm-0  float-right  role="button"
              <%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </a>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>
<br>
<div class="d-flex justify-content-center align-items-center">
  <%= will_paginate(@apartment, :renderer => WillPaginate::ActionView::LinkRenderer) %>

</div>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/search.html.erb
<%= render 'form', apartment: nil%> 

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rooms:</strong>
  <%= @apartment.rooms %>
</p>

<p>
  <strong>Paths:</strong>
  <%= @apartment.paths %>
</p>

<p>
  <strong>User:</strong>
  <%= @apartment.user.email %>
</p>

<% if current_user && current_user.id == @apartment.user.id %>
  <%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<% end %>
<%= link_to 'Back', apartments_path %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <img src="https://yallasa7el.com/logo/logo.png" alt="yallasa7el" class="navbar-brand" height="75px" width="85px">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to "home", root_path%> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "apartments", apartments_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Search", new_search_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "offer apartment for rent", new_apartment_path%></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <% if current_user %>
        <a class="btn btn-outline-dark my-2 my-sm-0"  role="button"
          <%= link_to "sign out", destroy_user_session_path, method: :delete%>
        </a>
      <% else %>
        <a class="nav-link" <%= link_to 'sign in ', new_user_session_path %> </a>
        <a class="nav-link" <%= link_to 'sign up ', new_user_registration_path %> </a>
      <% end %>

    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yallasa7el</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render :partial =>'searches/search',:locals => {:search => Search.new}%>

app/views/searches/_search.html.erb
<h3 class="d-flex justify-content-center align-items-center">Find your perfect sa7el rental easier than ever!</h3>
<%= bootstrap_form_for search do |f| %>
  <div class="field">
    <%= f.text_field :destnation,  placeholder:  "Enter the destination..."%>
  </div>
  <div class="field">
    <%= f.number_field :rooms, placeholder:  "Number of Rooms..."%>
  </div>

  <div class="field">
    <%= f.number_field :pathes, placeholder:  "Number of pathrooms..."%>
  </div>

  <div class="d-flex justify-content-center align-items-center actions"><%= f.submit "Search" %></div>
<% end %>

app/views/searches/new.html.erb
<%= render :partial => 'search',:locals => {:search => @search}%>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= link_to "Advanced Search", new_search_path %></p>

<a class="btn btn-outline-dark my-2 my-sm-0  float-right  role="button"
  <%= link_to 'Add Apartment', new_apartment_path %>
</a>
<h1>Apartments</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Destination</th>
      <th>Owner Name</th>
      <th>Owner phone</th>
      <th>Rooms</th>
      <th>Paths</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search.apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.destination %></td>
        <td><%= apartment.user.name %></td>
        <td><%= apartment.user.phone_number %></td>
        <td><%= apartment.rooms %></td>
        <td><%= apartment.paths %></td>
        <td>
          <a class="btn btn-info my-2 my-sm-0  float-right  role="button"
            <%= link_to 'Show', apartment %></td>
          </a>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>